const C = window.BeatVisionContracts;
const $ = id => document.getElementById(id);
const state = {running:false,mode:null,stage:-1,world:null,storyboard:null,assets:null,images:null,motion:null,audio:null,capabilities:null};

function project(){return {song_title:$('songTitle').value.trim(),style:$('style').value.trim(),lyrics:$('lyrics').value.trim()};}
function log(message,data){const stamp=new Date().toLocaleTimeString();$('log').textContent += `\n[${stamp}] ${message}`+(data?`\n${JSON.stringify(data,null,2)}`:'');$('log').scrollTop=$('log').scrollHeight;}
function renderStages(active=-1){$('pipeline').innerHTML=C.stages.map((s,i)=>`<article class="stage ${i<active?'done':''} ${i===active?'running':''}"><span class="num">${i+1}</span><strong>${s[1]}</strong><small>${s[2].toUpperCase()}</small></article>`).join('');}
function gateway(){return sessionStorage.getItem('beatvision_gateway')||$('gateway').value.trim().replace(/\/$/,'');}
function gatewayHeaders(){const token=$('gatewayToken').value.trim();return {'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})};}
async function gatewayGet(path){const base=gateway();if(!base)throw new Error('No gateway URL configured.');const r=await fetch(base+path,{headers:gatewayHeaders()});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={raw:text}}if(!r.ok)throw new Error(`${r.status}: ${d.error||text}`);return d;}
async function callGateway(operation,payload){const base=gateway();if(!base)throw new Error('No gateway URL configured.');const spec=C.operations[operation];if(!spec)throw new Error(`Unknown operation: ${operation}`);const requestId=crypto.randomUUID();const started=performance.now();const response=await fetch(base+spec.path,{method:'POST',headers:{...gatewayHeaders(),'X-BeatVision-Contract':C.version,'X-BeatVision-Request':requestId},body:JSON.stringify({contract_version:C.version,operation,payload})});const elapsed=Math.round(performance.now()-started);const text=await response.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}};if(!response.ok)throw new Error(`${response.status}: ${data.error||text}`);log(`${operation} completed in ${elapsed}ms`,data);return data.result??data;}

function demo(operation,payload){const seed=`${payload.song_title}|${payload.style}|${payload.lyrics.length}`;const world={title:'NEON AFTERIMAGE',logline:'A restless city turns broken signals, rain and memory into a living visual world.',palette:['midnight blue','wet steel','electric cyan','ember red'],tone:'dark, cinematic, industrial'};if(operation==='analyzeAudio')return {duration_seconds:214,bpm:104,sections:['intro','verse','chorus','bridge','finale'],energy_curve:[.2,.5,.9,.65,1]};if(operation==='revealWorld')return world;if(operation==='worldAssets')return {characters:['Lead performer'],environments:['Rain-soaked industrial city','Signal-lit interior'],style_bible:world};if(operation==='storyboard')return {scenes:[1,2,3,4,5,6,7].map(n=>({scene:n,description:`Scene ${n}: ${world.logline}`}))};if(operation==='sceneImages')return {images:[1,2,3,4,5,6,7].map(n=>({scene:n,status:'generated',image_url:`demo://scene-${n}`}))};if(operation==='animate')return {clips:[1,2,3,4,5,6,7].map(n=>({scene:n,status:'animated',video_url:`demo://motion-${n}`}))};if(operation==='assemble')return {status:'assembled',preview_url:'demo://beatvision-preview.mp4',duration_seconds:214};if(operation==='storeAsset')return {stored:true,asset_id:`demo-${seed}`};return {ok:true,seed};}
async function execute(operation,payload,mode='live'){if(mode==='demo'){await new Promise(r=>setTimeout(r,300));return demo(operation,payload)}return await callGateway(operation,payload);}
function hasPrereq(operation){const req={revealWorld:!!state.audio,worldAssets:!!state.world,storyboard:!!state.assets,sceneImages:!!state.storyboard,animate:!!state.images,assemble:!!state.motion,storeAsset:true};return req[operation]!==false;}
async function runPipeline(mode){if(state.running)return;state.running=true;state.mode=mode;$('runPipeline').disabled=true;$('runDemo').disabled=true;$('gatewayToken').disabled=mode==='demo';const p=project();$('log').textContent='';log(`Starting ${mode==='demo'?'deterministic':'live provider'} pipeline.`);try{renderStages(0);state.audio=await execute('analyzeAudio',p,mode);renderStages(1);state.world=await execute('revealWorld',{...p,audio:state.audio},mode);renderStages(2);state.assets=await execute('worldAssets',{...p,world:state.world},mode);renderStages(3);state.storyboard=await execute('storyboard',{...p,world:state.world,assets:state.assets},mode);renderStages(4);state.images=await execute('sceneImages',{...p,world:state.world,assets:state.assets,storyboard:state.storyboard},mode);renderStages(5);state.motion=await execute('animate',{...p,storyboard:state.storyboard,images:state.images},mode);renderStages(6);const assembled=await execute('assemble',{...p,audio:state.audio,motion:state.motion},mode);renderStages(7);log('PIPELINE COMPLETE',assembled);$('gatewayStatus').textContent=mode==='demo'?'Gateway: deterministic demo':'Gateway: live pipeline complete';}catch(e){log(`PIPELINE STOPPED: ${e.message}`);$('gatewayStatus').textContent='Gateway: pipeline failed';}finally{state.running=false;$('runPipeline').disabled=false;$('runDemo').disabled=false;}}
async function checkGateway(){const base=$('gateway').value.trim().replace(/\/$/,'');if(!base){$('gatewayStatus').textContent='Gateway: URL required';return}sessionStorage.setItem('beatvision_gateway',base);try{const [health,caps]=await Promise.all([gatewayGet('/health'),gatewayGet('/v1/capabilities')]);state.capabilities=caps.capabilities||{};const configured=Object.entries(state.capabilities).filter(([,v])=>v.configured).map(([k])=>k);$('gatewayStatus').textContent=`Gateway: online • ${configured.length}/5 capabilities configured`;log('Gateway verified', {health,capabilities:state.capabilities});renderCapabilities();}catch(e){state.capabilities=null;$('gatewayStatus').textContent='Gateway: unreachable or unauthorized';log('Gateway check failed: '+e.message);renderCapabilities();}}
function buildCaps(){const items=[['analyzeAudio','Audio intelligence','Analyze structure, timing, BPM and energy.'],['revealWorld','Language / World','Turn lyrics and audio context into the visual world.'],['worldAssets','Image / Assets','Generate character and environment assets.'],['storyboard','Language / Storyboard','Create scenes and continuity direction.'],['sceneImages','Image / Scenes','Generate production-ready scene imagery.'],['animate','Video / Motion','Animate approved scene images.'],['assemble','Video / Assembly','Assemble motion clips against the song.'],['storeAsset','Storage / Delivery','Persist an output or asset through the provider gateway.']];$('capabilities').innerHTML=items.map(([op,name,desc])=>`<article class="cap"><h3>${name}</h3><p>${desc}</p><button data-op="${op}">Run capability</button></article>`).join('');document.querySelectorAll('[data-op]').forEach(b=>b.onclick=async()=>{const op=b.dataset.op;if(!hasPrereq(op)){log(`${op} blocked: run the pipeline prerequisites first.`);return}b.disabled=true;try{const p=project();const payload={...p,world:state.world,assets:state.assets,storyboard:state.storyboard,images:state.images,motion:state.motion,audio:state.audio};const mode=gateway()?'live':'demo';const result=await execute(op,payload,mode);log(`${op} result`,result)}catch(e){log(`${op} failed: ${e.message}`)}finally{b.disabled=false}});renderCapabilities();}
function renderCapabilities(){document.querySelectorAll('.cap').forEach(card=>{const button=card.querySelector('button');const op=button?.dataset.op;if(!button||!state.capabilities)return;const capability=C.operations[op]?.capability;const configured=state.capabilities[capability]?.configured;button.title=configured?'Provider configured':'Provider not configured';if(gateway()&&!configured&&state.mode!=='demo')button.disabled=true;});}
$('checkGateway').onclick=checkGateway;$('gateway').onchange=()=>sessionStorage.setItem('beatvision_gateway',$('gateway').value.trim().replace(/\/$/,''));$('runPipeline').onclick=()=>runPipeline('live');$('runDemo').onclick=()=>runPipeline('demo');$('clearLog').onclick=()=>$('log').textContent='Ready.';if(sessionStorage.getItem('beatvision_gateway'))$('gateway').value=sessionStorage.getItem('beatvision_gateway');buildCaps();renderStages();
