interface Env {
  ALLOWED_ORIGIN?: string;
  LANGUAGE_PROVIDER_URL?: string;
  LANGUAGE_PROVIDER_TOKEN?: string;
  LANGUAGE_PROVIDER_MODEL?: string;
  LANGUAGE_PROVIDER?: string;
  IMAGE_PROVIDER_URL?: string;
  VIDEO_PROVIDER_URL?: string;
  AUDIO_PROVIDER_URL?: string;
  STORAGE_PROVIDER_URL?: string;
  IMAGE_PROVIDER_TOKEN?: string;
  VIDEO_PROVIDER_TOKEN?: string;
  AUDIO_PROVIDER_TOKEN?: string;
  STORAGE_PROVIDER_TOKEN?: string;
  GATEWAY_TOKEN?: string;
}

type Capability = 'language'|'image'|'video'|'audio'|'storage';
const CONTRACT_VERSION='1.1';
const MAX_BODY_BYTES=8_000_000;
const UPSTREAM_TIMEOUT_MS=45_000;
const HF_CHAT_URL='https://router.huggingface.co/v1/chat/completions';
const HF_CHAT_MODEL='openai/gpt-oss-120b:fastest';
const HF_IMAGE_URL='https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-dev';
const HF_AUDIO_URL='https://router.huggingface.co/hf-inference/models/openai/whisper-large-v3';
const routes:Record<string,Capability>={'/v1/language/world':'language','/v1/language/storyboard':'language','/v1/image/world-assets':'image','/v1/image/scenes':'image','/v1/video/animate':'video','/v1/video/assemble':'video','/v1/audio/analyze':'audio','/v1/storage/asset':'storage'};
const operations:Record<string,string>={'/v1/language/world':'revealWorld','/v1/language/storyboard':'storyboard','/v1/image/world-assets':'worldAssets','/v1/image/scenes':'sceneImages','/v1/video/animate':'animate','/v1/video/assemble':'assemble','/v1/audio/analyze':'analyzeAudio','/v1/storage/asset':'storeAsset'};
function cors(r:Request,e:Env):Record<string,string>{const o=r.headers.get('Origin')||'',a=e.ALLOWED_ORIGIN?.split(',').map(x=>x.trim()).filter(Boolean)||[];if(a.length&&o&&!a.includes(o))return {'Vary':'Origin'};return {'Access-Control-Allow-Origin':o||(a[0]||'*'),'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-BeatVision-Contract,Authorization,X-BeatVision-Request','Access-Control-Max-Age':'86400'}}
function json(r:Request,e:Env,d:unknown,s=200,x:Record<string,string>={}){return new Response(JSON.stringify(d,null,2),{status:s,headers:{'Content-Type':'application/json',...cors(r,e),...x}})}
function requestId(r:Request){return r.headers.get('X-BeatVision-Request')||crypto.randomUUID()}
function authorized(r:Request,e:Env){return !e.GATEWAY_TOKEN||r.headers.get('Authorization')===`Bearer ${e.GATEWAY_TOKEN}`}
function safeEndpoint(v?:string){try{const u=new URL(v||'');return ['https:','http:'].includes(u.protocol)?u.toString():null}catch{return null}}
function allowedOrigin(r:Request,e:Env){const a=e.ALLOWED_ORIGIN?.split(',').map(x=>x.trim()).filter(Boolean)||[],o=r.headers.get('Origin');return !a.length||!o||a.includes(o)}
function languageConfig(e:Env){return{url:safeEndpoint(e.LANGUAGE_PROVIDER_URL)||HF_CHAT_URL,token:e.LANGUAGE_PROVIDER_TOKEN,model:e.LANGUAGE_PROVIDER_MODEL||HF_CHAT_MODEL,provider:e.LANGUAGE_PROVIDER||'huggingface'}}
function hfImageConfig(e:Env){return{url:safeEndpoint(e.IMAGE_PROVIDER_URL)||HF_IMAGE_URL,token:e.IMAGE_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN,model:'black-forest-labs/FLUX.1-dev',provider:e.IMAGE_PROVIDER_URL?'configured':'huggingface'}}
function hfAudioConfig(e:Env){return{url:safeEndpoint(e.AUDIO_PROVIDER_URL)||HF_AUDIO_URL,token:e.AUDIO_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN,model:'openai/whisper-large-v3',provider:e.AUDIO_PROVIDER_URL?'configured':'huggingface'}}
function languageMessages(op:string,p:any){const system='You are the BeatVision visual-world director. Return ONLY valid JSON matching the requested schema. Preserve creative intent, continuity, and production usefulness. Do not invent lyrics that are not supplied.';if(op==='revealWorld')return[{role:'system',content:system+' For revealWorld return {title,logline,palette:[string],tone,visual_language,locations:[string],character_concept,continuity_rules:[string],visual_motifs:[string]}'},{role:'user',content:JSON.stringify({task:'revealWorld',song_title:p.song_title,style:p.style,lyrics:p.lyrics,audio:p.audio})}];if(op==='storyboard')return[{role:'system',content:system+' For storyboard return {scenes:[{scene,description,emotion,location,visual_direction,transition,continuity_notes}]}'},{role:'user',content:JSON.stringify({task:'storyboard',song_title:p.song_title,style:p.style,lyrics:p.lyrics,world:p.world,assets:p.assets,audio:p.audio})}];return[{role:'system',content:system+' For scene direction return {scenes:[{scene,prompt,camera,lighting,action,continuity_notes}]}'},{role:'user',content:JSON.stringify({task:op,...p})}]}
function extractText(x:any){return x?.choices?.[0]?.message?.content||x?.output_text||x?.choices?.[0]?.text||''}
function parseModelJson(t:string){const c=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(c)}catch{return{raw:c}}}
function imagePrompt(op:string,p:any){if(op==='worldAssets')return `BeatVision character and environment concept art. ${p.style||''}. World: ${JSON.stringify(p.world||{}).slice(0,6000)}. Cinematic music video pre-production, consistent character design, production concept art.`;return `BeatVision production scene image. ${p.style||''}. Scene direction: ${JSON.stringify(p.storyboard||{}).slice(0,7000)}. World: ${JSON.stringify(p.world||{}).slice(0,4000)}. Cinematic music video frame, strong composition, continuity-focused.`}
function base64Bytes(v:string){const b=v.includes(',')?v.split(',').pop()!:v;const raw=atob(b),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
export default {async fetch(request:Request,env:Env):Promise<Response>{
 const rid=requestId(request);if(request.method==='OPTIONS')return allowedOrigin(request,env)?new Response(null,{status:204,headers:cors(request,env)}):new Response('Forbidden',{status:403});if(!allowedOrigin(request,env))return json(request,env,{ok:false,error:'Origin not allowed.',request_id:rid},403);const url=new URL(request.url);
 if(request.method==='GET'&&url.pathname==='/health')return json(request,env,{ok:true,name:'BeatVision Provider Gateway',contract_version:CONTRACT_VERSION,request_id:rid});
 if(request.method==='GET'&&url.pathname==='/v1/capabilities'){if(!authorized(request,env))return json(request,env,{ok:false,error:'Unauthorized.',request_id:rid},401);const configs:{cap:Capability,configured:boolean,provider:string|null}[]=[{cap:'language',configured:Boolean(languageConfig(env).token),provider:languageConfig(env).token?languageConfig(env).provider:null},{cap:'image',configured:Boolean(hfImageConfig(env).token),provider:hfImageConfig(env).token?'huggingface':null},{cap:'audio',configured:Boolean(hfAudioConfig(env).token),provider:hfAudioConfig(env).token?'huggingface':null},{cap:'video',configured:Boolean(env.VIDEO_PROVIDER_URL),provider:safeEndpoint(env.VIDEO_PROVIDER_URL)?new URL(env.VIDEO_PROVIDER_URL!).hostname:null},{cap:'storage',configured:Boolean(env.STORAGE_PROVIDER_URL),provider:safeEndpoint(env.STORAGE_PROVIDER_URL)?new URL(env.STORAGE_PROVIDER_URL!).hostname:null}];return json(request,env,{ok:true,contract_version:CONTRACT_VERSION,capabilities:Object.fromEntries(configs.map(x=>[x.cap,{configured:x.configured,provider:x.provider}])),request_id:rid})}
 const capability=routes[url.pathname];if(!capability)return json(request,env,{ok:false,error:'Route not found.',request_id:rid},404);if(request.method!=='POST')return json(request,env,{ok:false,error:'POST required.',request_id:rid},405);if(!authorized(request,env))return json(request,env,{ok:false,error:'Unauthorized.',request_id:rid},401);const length=Number(request.headers.get('Content-Length')||0);if(length>MAX_BODY_BYTES)return json(request,env,{ok:false,error:'Request body too large.',request_id:rid},413);let body:any;try{body=await request.json()}catch{return json(request,env,{ok:false,error:'Invalid JSON body.',request_id:rid},400)}if(JSON.stringify(body).length>MAX_BODY_BYTES)return json(request,env,{ok:false,error:'Request body too large.',request_id:rid},413);if(body?.contract_version!==CONTRACT_VERSION)return json(request,env,{ok:false,error:`Unsupported BeatVision contract version. Expected ${CONTRACT_VERSION}.`,request_id:rid},400);if(body?.operation!==operations[url.pathname])return json(request,env,{ok:false,error:'Operation does not match gateway route.',request_id:rid},400);const started=Date.now();
 if(capability==='language'){const cfg=languageConfig(env);if(!cfg.token)return json(request,env,{ok:false,error:'No language provider token configured.',capability,mode:'unconfigured',provider:cfg.provider,request_id:rid},503);const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const u=await fetch(cfg.url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${cfg.token}`,'X-BeatVision-Capability':'language','X-BeatVision-Operation':body.operation,'X-BeatVision-Request':rid},body:JSON.stringify({model:cfg.model,messages:languageMessages(body.operation,body.payload),temperature:.7}),signal:ctl.signal});const text=await u.text();let result:any;try{result=JSON.parse(text)}catch{result={raw:text.slice(0,20000)}}const content=extractText(result),parsed=content?parseModelJson(content):result;return json(request,env,{ok:u.ok,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,model:cfg.model,latency_ms:Date.now()-started,request_id:rid,result:parsed,provider_response:result},u.status,{'X-BeatVision-Request':rid})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(request,env,{ok:false,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,latency_ms:Date.now()-started,request_id:rid,error:timed?'Language provider timed out.':'Language provider request failed.'},timed?504:502,{'X-BeatVision-Request':rid})}finally{clearTimeout(to)}}
 if(capability==='image'){const cfg=hfImageConfig(env);if(!cfg.token)return json(request,env,{ok:false,error:'No image provider token configured.',capability,mode:'unconfigured',request_id:rid},503);const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const prompt=imagePrompt(body.operation,body.payload||{}),u=await fetch(cfg.url,{method:'POST',headers:{Authorization:`Bearer ${cfg.token}`,'Content-Type':'application/json','X-BeatVision-Request':rid},body:JSON.stringify({inputs:prompt,parameters:{width:1024,height:576,num_inference_steps:20}}),signal:ctl.signal});const ct=u.headers.get('content-type')||'';if(!u.ok){const text=await u.text();return json(request,env,{ok:false,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,latency_ms:Date.now()-started,request_id:rid,error:`Image provider returned ${u.status}.`,provider_response:text.slice(0,4000)},u.status,{'X-BeatVision-Request':rid})}if(!ct.startsWith('image/')){const text=await u.text();return json(request,env,{ok:false,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,latency_ms:Date.now()-started,request_id:rid,error:'Image provider did not return an image.',provider_response:text.slice(0,4000)},502,{'X-BeatVision-Request':rid})}const bytes=new Uint8Array(await u.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const dataUrl=`data:${ct};base64,${btoa(binary)}`;return json(request,env,{ok:true,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,model:cfg.model,latency_ms:Date.now()-started,request_id:rid,result:{operation:body.operation,status:'generated',image_url:dataUrl,mime_type:ct}},200,{'X-BeatVision-Request':rid})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(request,env,{ok:false,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,latency_ms:Date.now()-started,request_id:rid,error:timed?'Image provider timed out.':'Image provider request failed.'},timed?504:502,{'X-BeatVision-Request':rid})}finally{clearTimeout(to)}}
 if(capability==='audio'){const cfg=hfAudioConfig(env);if(!cfg.token)return json(request,env,{ok:false,error:'No audio provider token configured.',capability,mode:'unconfigured',request_id:rid},503);const p=body.payload||{},audio=p.audio_base64||p.audio_data;if(!audio)return json(request,env,{ok:false,error:'Audio provider requires audio_base64/audio_data for live analysis.',capability,request_id:rid},400);const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const u=await fetch(cfg.url,{method:'POST',headers:{Authorization:`Bearer ${cfg.token}`,'Content-Type':p.audio_mime_type||'audio/mpeg','X-BeatVision-Request':rid},body:base64Bytes(audio),signal:ctl.signal});const text=await u.text();let result:any;try{result=JSON.parse(text)}catch{result={raw:text.slice(0,10000)}}return json(request,env,{ok:u.ok,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,model:cfg.model,latency_ms:Date.now()-started,request_id:rid,result:{...result,analysis:{duration_seconds:p.duration_seconds??null,bpm:p.bpm??null,energy_curve:p.energy_curve??null,source:'Hugging Face ASR + browser audio metadata'}}},u.status,{'X-BeatVision-Request':rid})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(request,env,{ok:false,contract_version:CONTRACT_VERSION,capability,provider:cfg.provider,latency_ms:Date.now()-started,request_id:rid,error:timed?'Audio provider timed out.':'Audio provider request failed.'},timed?504:502,{'X-BeatVision-Request':rid})}finally{clearTimeout(to)}}
 const [configuredEndpoint,token]=capability==='video'?[env.VIDEO_PROVIDER_URL,env.VIDEO_PROVIDER_TOKEN]:[env.STORAGE_PROVIDER_URL,env.STORAGE_PROVIDER_TOKEN],endpoint=safeEndpoint(configuredEndpoint);if(!endpoint)return json(request,env,{ok:false,error:`No valid ${capability} provider configured.`,capability,mode:'unconfigured',request_id:rid},503);const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const headers:Record<string,string>={'Content-Type':'application/json','X-BeatVision-Capability':capability,'X-BeatVision-Operation':body.operation,'X-BeatVision-Request':rid};if(token)headers.Authorization=`Bearer ${token}`;const u=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify({contract_version:CONTRACT_VERSION,capability,operation:body.operation,payload:body.payload,request_id:rid}),signal:ctl.signal});const text=await u.text();let result:any;try{result=JSON.parse(text)}catch{result={raw:text.slice(0,20000)}}return json(request,env,{ok:u.ok,contract_version:CONTRACT_VERSION,capability,latency_ms:Date.now()-started,request_id:rid,result},u.status,{'X-BeatVision-Request':rid})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(request,env,{ok:false,contract_version:CONTRACT_VERSION,capability,latency_ms:Date.now()-started,request_id:rid,error:timed?'Upstream provider timed out.':'Upstream provider request failed.'},timed?504:502,{'X-BeatVision-Request':rid})}finally{clearTimeout(to)}}};