import { InferenceClient } from '@huggingface/inference';

interface Env {
  ALLOWED_ORIGIN?: string; LANGUAGE_PROVIDER_URL?: string; LANGUAGE_PROVIDER_TOKEN?: string; LANGUAGE_PROVIDER_MODEL?: string; LANGUAGE_PROVIDER?: string;
  IMAGE_PROVIDER_URL?: string; IMAGE_PROVIDER_TOKEN?: string; IMAGE_PROVIDER?: string; IMAGE_PROVIDER_MODEL?: string;
  VIDEO_PROVIDER_URL?: string; VIDEO_PROVIDER_TOKEN?: string; VIDEO_PROVIDER?: string; VIDEO_PROVIDER_MODEL?: string;
  AUDIO_PROVIDER_URL?: string; STORAGE_PROVIDER_URL?: string;
  AUDIO_PROVIDER_TOKEN?: string; STORAGE_PROVIDER_TOKEN?: string; GATEWAY_TOKEN?: string;
}
type Capability='language'|'image'|'video'|'audio'|'storage';
const CONTRACT_VERSION='1.1', MAX_BODY_BYTES=8_000_000, UPSTREAM_TIMEOUT_MS=45_000, AUDIO_TIMEOUT_MS=120_000, VIDEO_TIMEOUT_MS=120_000;
const HF_CHAT_URL='https://router.huggingface.co/v1/chat/completions', HF_CHAT_MODEL='openai/gpt-oss-120b:fastest';
const HF_IMAGE_MODEL='black-forest-labs/FLUX.1-schnell';
const HF_VIDEO_MODEL='Wan-AI/Wan2.1-I2V-14B-720P';
const HF_AUDIO_URL='https://router.huggingface.co/hf-inference/models/openai/whisper-large-v3-turbo';
const POLLINATIONS_IMAGE_URL='https://gen.pollinations.ai/image/';
const routes:Record<string,Capability>={'/v1/language/world':'language','/v1/language/storyboard':'language','/v1/image/world-assets':'image','/v1/image/scenes':'image','/v1/video/animate':'video','/v1/video/assemble':'video','/v1/audio/analyze':'audio','/v1/storage/asset':'storage'};
const ops:Record<string,string>={'/v1/language/world':'revealWorld','/v1/language/storyboard':'storyboard','/v1/image/world-assets':'worldAssets','/v1/image/scenes':'sceneImages','/v1/video/animate':'animate','/v1/video/assemble':'assemble','/v1/audio/analyze':'analyzeAudio','/v1/storage/asset':'storeAsset'};
function cors(r:Request,e:Env){const o=r.headers.get('Origin')||'',a=e.ALLOWED_ORIGIN?.split(',').map(x=>x.trim()).filter(Boolean)||[];return{'Access-Control-Allow-Origin':o&&(!a.length||a.includes(o))?o:(a[0]||'*'),'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-BeatVision-Contract,Authorization,X-BeatVision-Request','Access-Control-Max-Age':'86400'}}
function json(r:Request,e:Env,d:unknown,s=200,x:Record<string,string>={}){return new Response(JSON.stringify(d,null,2),{status:s,headers:{'Content-Type':'application/json',...cors(r,e),...x}})}
function endpoint(v?:string){try{const u=new URL(v||'');return['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
function auth(r:Request,e:Env){return!e.GATEWAY_TOKEN||r.headers.get('Authorization')===`Bearer ${e.GATEWAY_TOKEN}`}
function cfg(e:Env){const imageProvider=e.IMAGE_PROVIDER||'pollinations';const videoProvider=e.VIDEO_PROVIDER||'auto';return{lang:{url:endpoint(e.LANGUAGE_PROVIDER_URL)||HF_CHAT_URL,token:e.LANGUAGE_PROVIDER_TOKEN,model:e.LANGUAGE_PROVIDER_MODEL||HF_CHAT_MODEL,provider:e.LANGUAGE_PROVIDER||'huggingface'},image:{url:endpoint(e.IMAGE_PROVIDER_URL),token:e.IMAGE_PROVIDER_TOKEN,model:e.IMAGE_PROVIDER_MODEL||(imageProvider==='pollinations'?'flux':HF_IMAGE_MODEL),provider:imageProvider},video:{url:endpoint(e.VIDEO_PROVIDER_URL),token:e.VIDEO_PROVIDER_TOKEN||(videoProvider==='pollinations'?e.IMAGE_PROVIDER_TOKEN:undefined),model:e.VIDEO_PROVIDER_MODEL||HF_VIDEO_MODEL,provider:videoProvider},audio:{url:endpoint(e.AUDIO_PROVIDER_URL)||HF_AUDIO_URL,token:e.AUDIO_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN,model:'openai/whisper-large-v3-turbo',provider:e.AUDIO_PROVIDER_URL?'configured':'huggingface'}}}
function safePayload(p:any){if(!p||typeof p!=='object')return{};const q=JSON.parse(JSON.stringify(p));for(const k of ['audio_base64','audio_data','file_base64','raw_audio'])if(k in q)delete q[k];if(q.audio&&typeof q.audio==='object'){for(const k of ['audio_base64','audio_data','file_base64','raw_audio'])delete q.audio[k];}return q}
function clip(v:any,n:number){return typeof v==='string'?v.slice(0,n):v}
function compactWorld(v:any){if(!v||typeof v!=='object')return v;return{title:clip(v.title,500),logline:clip(v.logline,3000),palette:Array.isArray(v.palette)?v.palette.slice(0,24):v.palette,tone:clip(v.tone,2000),visual_language:clip(v.visual_language,5000),locations:Array.isArray(v.locations)?v.locations.slice(0,12):v.locations,character_concept:clip(v.character_concept,5000),continuity_rules:Array.isArray(v.continuity_rules)?v.continuity_rules.slice(0,30):v.continuity_rules,visual_motifs:Array.isArray(v.visual_motifs)?v.visual_motifs.slice(0,30):v.visual_motifs}}
function compactAudio(v:any){if(!v||typeof v!=='object')return v;return{duration_seconds:v.duration_seconds??null,bpm:v.bpm??null,sections:Array.isArray(v.sections)?v.sections.slice(0,30):v.sections,energy_curve:Array.isArray(v.energy_curve)?v.energy_curve.slice(0,120):v.energy_curve,transcript:clip(v.text||v.transcript||v.result?.text||'',12000)}}
function compactAssets(v:any){if(!v||typeof v!=='object')return v;return{characters:Array.isArray(v.characters)?v.characters.slice(0,20):v.characters,environments:Array.isArray(v.environments)?v.environments.slice(0,20):v.environments,style_bible:compactWorld(v.style_bible)}}
function compactStoryboard(v:any){if(!v||typeof v!=='object')return v;return{scenes:Array.isArray(v.scenes)?v.scenes.slice(0,24).map((s:any)=>({scene:s.scene,description:clip(s.description,2500),emotion:clip(s.emotion,500),location:clip(s.location,500),visual_direction:clip(s.visual_direction,3000),transition:clip(s.transition,1000),continuity_notes:clip(s.continuity_notes,2000)})):v.scenes}}
function messages(op:string,p:any){const clean=safePayload(p),system='You are the BeatVision visual-world director. Return ONLY valid JSON. Preserve creative intent, continuity, and production usefulness. Do not invent lyrics.';const base={song_title:clip(clean.song_title,500),style:clip(clean.style,1500),lyrics:clip(clean.lyrics,12000)};if(op==='revealWorld')return[{role:'system',content:system+' Return {title,logline,palette,tone,visual_language,locations,character_concept,continuity_rules,visual_motifs}.'},{role:'user',content:JSON.stringify({task:op,...base,audio:compactAudio(clean.audio)})}];return[{role:'system',content:system+' Return {scenes:[{scene,description,emotion,location,visual_direction,transition,continuity_notes}]}.'},{role:'user',content:JSON.stringify({task:op,...base,world:compactWorld(clean.world),assets:compactAssets(clean.assets)})}]}
function parse(t:string){const s=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{return{raw:s}}}
function imagePrompt(p:any){return`BeatVision cinematic music video concept art. 16:9 cinematic composition. Style: ${clip(p?.style||'',1500)}. World: ${JSON.stringify(compactWorld(p?.world||{}))}. Storyboard: ${JSON.stringify(compactStoryboard(p?.storyboard||{}))}. Strong composition and character/environment continuity.`}
function dataUrlBlob(v:any){if(typeof v!=='string'||!v.startsWith('data:'))return null;const comma=v.indexOf(',');if(comma<0)return null;const mime=(v.slice(5,comma).split(';')[0]||'image/png');const raw=atob(v.slice(comma+1));const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:mime})}
function firstImage(p:any){const imgs=p?.images?.images||p?.images||[];const item=Array.isArray(imgs)?imgs[0]:null;return item?.image_url||item?.url||item?.data_url||null}
export default{async fetch(r:Request,e:Env){const id=r.headers.get('X-BeatVision-Request')||crypto.randomUUID(),u=new URL(r.url);if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r,e)});if(r.method==='GET'&&u.pathname==='/health')return json(r,e,{ok:true,name:'BeatVision Provider Gateway',contract_version:CONTRACT_VERSION,request_id:id});if(r.method==='GET'&&u.pathname==='/v1/capabilities'){if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);const c=cfg(e);return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capabilities:{language:{configured:!!c.lang.token,provider:c.lang.provider},image:{configured:!!c.image.token,provider:c.image.provider,model:c.image.model},audio:{configured:!!c.audio.token,provider:c.audio.provider},video:{configured:!!c.video.token,provider:c.video.provider,model:c.video.model},storage:{configured:!!endpoint(e.STORAGE_PROVIDER_URL),provider:e.STORAGE_PROVIDER_URL||null}},request_id:id})}const cap=routes[u.pathname];if(!cap)return json(r,e,{ok:false,error:'Route not found',request_id:id},404);if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);if(Number(r.headers.get('Content-Length')||0)>MAX_BODY_BYTES)return json(r,e,{ok:false,error:'Request body too large',request_id:id},413);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}if(JSON.stringify(body).length>MAX_BODY_BYTES)return json(r,e,{ok:false,error:'Request body too large',request_id:id},413);if(body?.contract_version!==CONTRACT_VERSION)return json(r,e,{ok:false,error:`Unsupported BeatVision contract version. Expected ${CONTRACT_VERSION}.`,request_id:id},400);if(body?.operation!==ops[u.pathname])return json(r,e,{ok:false,error:'Operation does not match gateway route',request_id:id},400);const start=Date.now(),c=cfg(e);
if(cap==='audio'){if(!c.audio.token)return json(r,e,{ok:false,error:'No audio provider token configured',capability:cap,request_id:id},503);const p=body.payload||{},input=p.audio_base64||p.audio_data;if(!input)return json(r,e,{ok:false,error:'Audio provider requires audio_base64/audio_data for live analysis',capability:cap,request_id:id},400);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),AUDIO_TIMEOUT_MS);try{const res=await fetch(c.audio.url!,{method:'POST',headers:{Authorization:`Bearer ${c.audio.token}`,'Content-Type':'application/json','X-BeatVision-Request':id},body:JSON.stringify({inputs:input.includes(',')?input.split(',').pop():input,parameters:{return_timestamps:true}}),signal:ctl.signal}),txt=await res.text();let result:any;try{result=JSON.parse(txt)}catch{result={raw:txt.slice(0,10000)}}return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:cap,provider:c.audio.provider,model:c.audio.model,latency_ms:Date.now()-start,request_id:id,result,analysis:{duration_seconds:p.duration_seconds??null,bpm:p.bpm??null,energy_curve:p.energy_curve??null,source:'Hugging Face ASR + browser audio metadata'}},res.status,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,contract_version:CONTRACT_VERSION,capability:cap,provider:c.audio.provider,model:c.audio.model,latency_ms:Date.now()-start,request_id:id,error:timed?'Audio provider timed out after 120 seconds':'Audio provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}
if(cap==='language'){if(!c.lang.token)return json(r,e,{ok:false,error:'No language provider token configured',capability:cap,request_id:id},503);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const clean=safePayload(body.payload||{}),msgs=messages(body.operation,clean),res=await fetch(c.lang.url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${c.lang.token}`,'X-BeatVision-Request':id},body:JSON.stringify({model:c.lang.model,messages:msgs,temperature:.7}),signal:ctl.signal}),txt=await res.text();let result:any;try{result=JSON.parse(txt)}catch{result={raw:txt}}const content=result?.choices?.[0]?.message?.content||'';return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:cap,provider:c.lang.provider,model:c.lang.model,latency_ms:Date.now()-start,request_id:id,result:content?parse(content):result},res.status,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,capability:cap,provider:c.lang.provider,latency_ms:Date.now()-start,request_id:id,error:timed?'Language provider timed out':'Language provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}
if(cap==='image'){if(!c.image.token)return json(r,e,{ok:false,error:'No image provider token configured. Configure IMAGE_PROVIDER_TOKEN in the deployed Worker.',capability:cap,provider:c.image.provider,request_id:id},503);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{let blob:Blob;if(c.image.provider==='pollinations'){const prompt=encodeURIComponent(imagePrompt(body.payload||{}));const target=`${POLLINATIONS_IMAGE_URL}${prompt}?model=${encodeURIComponent(c.image.model||'flux')}`;const res=await fetch(target,{method:'GET',headers:{Authorization:`Bearer ${c.image.token}`,'X-BeatVision-Request':id},signal:ctl.signal});if(!res.ok){const providerResponse=(await res.text()).slice(0,4000);return json(r,e,{ok:false,capability:cap,provider:'pollinations',model:c.image.model,latency_ms:Date.now()-start,request_id:id,error:`Pollinations image provider returned ${res.status}`,provider_response:providerResponse},res.status)}blob=await res.blob()}else if(c.image.url){const res=await fetch(c.image.url,{method:'POST',headers:{Authorization:`Bearer ${c.image.token}`,'Content-Type':'application/json','X-BeatVision-Request':id},body:JSON.stringify({inputs:imagePrompt(body.payload||{}),parameters:{width:1024,height:576,num_inference_steps:4}}),signal:ctl.signal});if(!res.ok){const providerResponse=(await res.text()).slice(0,4000);return json(r,e,{ok:false,capability:cap,provider:'configured',model:c.image.model,latency_ms:Date.now()-start,request_id:id,error:`Image provider returned ${res.status}`,provider_response:providerResponse},res.status)}blob=await res.blob()}else{const hf=new InferenceClient(c.image.token);blob=await hf.textToImage({model:c.image.model,provider:c.image.provider as any,inputs:imagePrompt(body.payload||{})},{outputType:'blob',wait_for_model:true} as any)}const data=new Uint8Array(await blob.arrayBuffer());let s='';for(let i=0;i<data.length;i+=32768)s+=String.fromCharCode(...data.subarray(i,i+32768));const ct=blob.type||'image/png';return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capability:cap,provider:c.image.provider,model:c.image.model,latency_ms:Date.now()-start,request_id:id,result:{status:'generated',image_url:`data:${ct};base64,${btoa(s)}`,mime_type:ct}},200,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';const msg=err instanceof Error?err.message:String(err);return json(r,e,{ok:false,capability:cap,provider:c.image.provider,model:c.image.model,latency_ms:Date.now()-start,request_id:id,error:timed?'Image provider timed out':`Image provider request failed: ${msg.slice(0,1500)}`},timed?504:502)}finally{clearTimeout(tm)}}
if(cap==='video'&&u.pathname==='/v1/video/animate'){if(!c.video.token)return json(r,e,{ok:false,error:'No video provider token configured for the selected video provider.',capability:cap,provider:c.video.provider,model:c.video.model,request_id:id},503);const p=body.payload||{},imageUrl=firstImage(p),image=dataUrlBlob(imageUrl);if(!image)return json(r,e,{ok:false,error:'Motion requires a generated scene image data URL.',capability:cap,provider:c.video.provider,model:c.video.model,request_id:id},400);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),VIDEO_TIMEOUT_MS);try{const hf=new InferenceClient(c.video.token);const prompt=`Animate this BeatVision scene with restrained cinematic camera motion, natural subject movement, atmospheric lighting and continuity. Style: ${clip(p.style||'',1000)}. World: ${clip(p.world?.logline||'',1500)}. Storyboard direction: ${clip(p.storyboard?.scenes?.[0]?.visual_direction||p.storyboard?.scenes?.[0]?.description||'',2000)}`;const blob=await hf.imageToVideo({inputs:image,model:c.video.model,provider:c.video.provider as any,prompt} as any,{outputType:'blob'} as any);const data=new Uint8Array(await blob.arrayBuffer());let s='';for(let i=0;i<data.length;i+=32768)s+=String.fromCharCode(...data.subarray(i,i+32768));const ct=blob.type||'video/mp4';return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capability:cap,provider:c.video.provider,model:c.video.model,latency_ms:Date.now()-start,request_id:id,result:{status:'animated',video_url:`data:${ct};base64,${btoa(s)}`,mime_type:ct}},200,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';const msg=err instanceof Error?err.message:String(err);return json(r,e,{ok:false,contract_version:CONTRACT_VERSION,capability:cap,provider:c.video.provider,model:c.video.model,latency_ms:Date.now()-start,request_id:id,error:timed?'Video provider timed out after 120 seconds':`Video provider request failed: ${msg.slice(0,2000)}`},timed?504:502)}finally{clearTimeout(tm)}}
const target=cap==='video'?endpoint(e.VIDEO_PROVIDER_URL):endpoint(e.STORAGE_PROVIDER_URL),token=cap==='video'?e.VIDEO_PROVIDER_TOKEN:e.STORAGE_PROVIDER_TOKEN;if(!target)return json(r,e,{ok:false,error:`No valid ${cap} provider configured`,capability:cap,mode:'unconfigured',request_id:id},503);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const h:Record<string,string>={'Content-Type':'application/json','X-BeatVision-Request':id};if(token)h.Authorization=`Bearer ${token}`;const res=await fetch(target,{method:'POST',headers:h,body:JSON.stringify({...body,request_id:id}),signal:ctl.signal}),txt=await res.text();let result:any;try{result=JSON.parse(txt)}catch{result={raw:txt.slice(0,20000)}}return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:cap,latency_ms:Date.now()-start,request_id:id,result},res.status,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,capability:cap,latency_ms:Date.now()-start,request_id:id,error:timed?'Upstream provider timed out':'Upstream provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}};