interface Env {
  ALLOWED_ORIGIN?: string; LANGUAGE_PROVIDER_URL?: string; LANGUAGE_PROVIDER_TOKEN?: string; LANGUAGE_PROVIDER_MODEL?: string; LANGUAGE_PROVIDER?: string;
  IMAGE_PROVIDER_URL?: string; VIDEO_PROVIDER_URL?: string; AUDIO_PROVIDER_URL?: string; STORAGE_PROVIDER_URL?: string;
  IMAGE_PROVIDER_TOKEN?: string; VIDEO_PROVIDER_TOKEN?: string; AUDIO_PROVIDER_TOKEN?: string; STORAGE_PROVIDER_TOKEN?: string; GATEWAY_TOKEN?: string;
}
type Capability='language'|'image'|'video'|'audio'|'storage';
const CONTRACT_VERSION='1.1', MAX_BODY_BYTES=8_000_000, UPSTREAM_TIMEOUT_MS=45_000, AUDIO_TIMEOUT_MS=120_000;
const HF_CHAT_URL='https://router.huggingface.co/v1/chat/completions', HF_CHAT_MODEL='openai/gpt-oss-120b:fastest';
const HF_IMAGE_MODEL='stabilityai/stable-diffusion-xl-base-1.0';
const HF_IMAGE_URL=`https://router.huggingface.co/hf-inference/models/${HF_IMAGE_MODEL}`;
const HF_AUDIO_URL='https://router.huggingface.co/hf-inference/models/openai/whisper-large-v3-turbo';
const routes:Record<string,Capability>={'/v1/language/world':'language','/v1/language/storyboard':'language','/v1/image/world-assets':'image','/v1/image/scenes':'image','/v1/video/animate':'video','/v1/video/assemble':'video','/v1/audio/analyze':'audio','/v1/storage/asset':'storage'};
const ops:Record<string,string>={'/v1/language/world':'revealWorld','/v1/language/storyboard':'storyboard','/v1/image/world-assets':'worldAssets','/v1/image/scenes':'sceneImages','/v1/video/animate':'animate','/v1/video/assemble':'assemble','/v1/audio/analyze':'analyzeAudio','/v1/storage/asset':'storeAsset'};
function cors(r:Request,e:Env){const o=r.headers.get('Origin')||'',a=e.ALLOWED_ORIGIN?.split(',').map(x=>x.trim()).filter(Boolean)||[];return{'Access-Control-Allow-Origin':o&&(!a.length||a.includes(o))?o:(a[0]||'*'),'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-BeatVision-Contract,Authorization,X-BeatVision-Request','Access-Control-Max-Age':'86400'}}
function json(r:Request,e:Env,d:unknown,s=200,x:Record<string,string>={}){return new Response(JSON.stringify(d,null,2),{status:s,headers:{'Content-Type':'application/json',...cors(r,e),...x}})}
function endpoint(v?:string){try{const u=new URL(v||'');return['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
function auth(r:Request,e:Env){return!e.GATEWAY_TOKEN||r.headers.get('Authorization')===`Bearer ${e.GATEWAY_TOKEN}`}
function cfg(e:Env){return{lang:{url:endpoint(e.LANGUAGE_PROVIDER_URL)||HF_CHAT_URL,token:e.LANGUAGE_PROVIDER_TOKEN,model:e.LANGUAGE_PROVIDER_MODEL||HF_CHAT_MODEL,provider:e.LANGUAGE_PROVIDER||'huggingface'},image:{url:endpoint(e.IMAGE_PROVIDER_URL)||HF_IMAGE_URL,token:e.IMAGE_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN,model:HF_IMAGE_MODEL,provider:e.IMAGE_PROVIDER_URL?'configured':'huggingface'},audio:{url:endpoint(e.AUDIO_PROVIDER_URL)||HF_AUDIO_URL,token:e.AUDIO_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN,model:'openai/whisper-large-v3-turbo',provider:e.AUDIO_PROVIDER_URL?'configured':'huggingface'}}}
function safePayload(p:any){if(!p||typeof p!=='object')return{};const q=JSON.parse(JSON.stringify(p));for(const k of ['audio_base64','audio_data','file_base64','raw_audio'])if(k in q)delete q[k];if(q.audio&&typeof q.audio==='object'){for(const k of ['audio_base64','audio_data','file_base64','raw_audio'])delete q.audio[k];}return q}
function messages(op:string,p:any){const clean=safePayload(p);const system='You are the BeatVision visual-world director. Return ONLY valid JSON. Preserve creative intent, continuity, and production usefulness. Do not invent lyrics.';if(op==='revealWorld')return[{role:'system',content:system+' Return {title,logline,palette,tone,visual_language,locations,character_concept,continuity_rules,visual_motifs}.'},{role:'user',content:JSON.stringify({task:op,...clean})}];return[{role:'system',content:system+' Return {scenes:[{scene,description,emotion,location,visual_direction,transition,continuity_notes}]}.'},{role:'user',content:JSON.stringify({task:op,...clean})}]}
function parse(t:string){const s=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{return{raw:s}}}
function b64bytes(v:string){const b=v.includes(',')?v.split(',').pop()!:v,raw=atob(b),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function imagePrompt(p:any){return`BeatVision cinematic music video concept art. Style: ${p?.style||''}. World: ${JSON.stringify(p?.world||{}).slice(0,6000)}. Storyboard: ${JSON.stringify(p?.storyboard||{}).slice(0,6000)}. Strong composition and character/environment continuity.`}
export default{async fetch(r:Request,e:Env){const id=r.headers.get('X-BeatVision-Request')||crypto.randomUUID(),u=new URL(r.url);if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r,e)});if(r.method==='GET'&&u.pathname==='/health')return json(r,e,{ok:true,name:'BeatVision Provider Gateway',contract_version:CONTRACT_VERSION,request_id:id});if(r.method==='GET'&&u.pathname==='/v1/capabilities'){if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);const c=cfg(e);return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capabilities:{language:{configured:!!c.lang.token,provider:c.lang.provider},image:{configured:!!c.image.token,provider:c.image.token?'huggingface':null,model:c.image.model},audio:{configured:!!c.audio.token,provider:c.audio.token?'huggingface':null},video:{configured:!!endpoint(e.VIDEO_PROVIDER_URL),provider:e.VIDEO_PROVIDER_URL||null},storage:{configured:!!endpoint(e.STORAGE_PROVIDER_URL),provider:e.STORAGE_PROVIDER_URL||null}},request_id:id})}const cap=routes[u.pathname];if(!cap)return json(r,e,{ok:false,error:'Route not found',request_id:id},404);if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);if(Number(r.headers.get('Content-Length')||0)>MAX_BODY_BYTES)return json(r,e,{ok:false,error:'Request body too large',request_id:id},413);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}if(JSON.stringify(body).length>MAX_BODY_BYTES)return json(r,e,{ok:false,error:'Request body too large',request_id:id},413);if(body?.contract_version!==CONTRACT_VERSION)return json(r,e,{ok:false,error:`Unsupported BeatVision contract version. Expected ${CONTRACT_VERSION}.`,request_id:id},400);if(body?.operation!==ops[u.pathname])return json(r,e,{ok:false,error:'Operation does not match gateway route',request_id:id},400);const start=Date.now(),c=cfg(e);
if(cap==='audio'){if(!c.audio.token)return json(r,e,{ok:false,error:'No audio provider token configured',capability:cap,request_id:id},503);const p=body.payload||{},input=p.audio_base64||p.audio_data;if(!input)return json(r,e,{ok:false,error:'Audio provider requires audio_base64/audio_data for live analysis',capability:cap,request_id:id},400);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),AUDIO_TIMEOUT_MS);try{const res=await fetch(c.audio.url,{method:'POST',headers:{Authorization:`Bearer ${c.audio.token}`,'Content-Type':'application/json','X-BeatVision-Request':id},body:JSON.stringify({inputs:input.includes(',')?input.split(',').pop():input,parameters:{return_timestamps:true}}),signal:ctl.signal}),txt=await res.text();let result:any;try{result=JSON.parse(txt)}catch{result={raw:txt.slice(0,10000)}}return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:cap,provider:c.audio.provider,model:c.audio.model,latency_ms:Date.now()-start,request_id:id,result,analysis:{duration_seconds:p.duration_seconds??null,bpm:p.bpm??null,energy_curve:p.energy_curve??null,source:'Hugging Face ASR + browser audio metadata'}},res.status,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,contract_version:CONTRACT_VERSION,capability:cap,provider:c.audio.provider,model:c.audio.model,latency_ms:Date.now()-start,request_id:id,error:timed?'Audio provider timed out after 120 seconds':'Audio provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}
if(cap==='language'){if(!c.lang.token)return json(r,e,{ok:false,error:'No language provider token configured',capability:cap,request_id:id},503);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const clean=safePayload(body.payload||{}),res=await fetch(c.lang.url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${c.lang.token}`,'X-BeatVision-Request':id},body:JSON.stringify({model:c.lang.model,messages:messages(body.operation,clean),temperature:.7}),signal:ctl.signal}),txt=await res.text();let result:any;try{result=JSON.parse(txt)}catch{result={raw:txt}}const content=result?.choices?.[0]?.message?.content||'';return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:cap,provider:c.lang.provider,model:c.lang.model,latency_ms:Date.now()-start,request_id:id,result:content?parse(content):result},res.status,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,capability:cap,provider:c.lang.provider,latency_ms:Date.now()-start,request_id:id,error:timed?'Language provider timed out':'Language provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}
if(cap==='image'){if(!c.image.token)return json(r,e,{ok:false,error:'No image provider token configured',capability:cap,request_id:id},503);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const res=await fetch(c.image.url,{method:'POST',headers:{Authorization:`Bearer ${c.image.token}`,'Content-Type':'application/json','X-BeatVision-Request':id},body:JSON.stringify({inputs:imagePrompt(body.payload||{}),parameters:{width:1024,height:576,num_inference_steps:20}}),signal:ctl.signal});if(!res.ok)return json(r,e,{ok:false,capability:cap,provider:c.image.provider,model:c.image.model,latency_ms:Date.now()-start,request_id:id,error:`Image provider returned ${res.status}`,provider_response:(await res.text()).slice(0,4000)},res.status);const ct=res.headers.get('content-type')||'image/png',data=new Uint8Array(await res.arrayBuffer());let s='';for(let i=0;i<data.length;i+=32768)s+=String.fromCharCode(...data.subarray(i,i+32768));return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capability:cap,provider:c.image.provider,model:c.image.model,latency_ms:Date.now()-start,request_id:id,result:{status:'generated',image_url:`data:${ct};base64,${btoa(s)}`,mime_type:ct}},200,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,capability:cap,provider:c.image.provider,model:c.image.model,latency_ms:Date.now()-start,request_id:id,error:timed?'Image provider timed out':'Image provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}
const target=cap==='video'?endpoint(e.VIDEO_PROVIDER_URL):endpoint(e.STORAGE_PROVIDER_URL),token=cap==='video'?e.VIDEO_PROVIDER_TOKEN:e.STORAGE_PROVIDER_TOKEN;if(!target)return json(r,e,{ok:false,error:`No valid ${cap} provider configured`,capability:cap,mode:'unconfigured',request_id:id},503);const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const h:Record<string,string>={'Content-Type':'application/json','X-BeatVision-Request':id};if(token)h.Authorization=`Bearer ${token}`;const res=await fetch(target,{method:'POST',headers:h,body:JSON.stringify({...body,request_id:id}),signal:ctl.signal}),txt=await res.text();let result:any;try{result=JSON.parse(txt)}catch{result={raw:txt.slice(0,20000)}}return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:cap,latency_ms:Date.now()-start,request_id:id,result},res.status,{'X-BeatVision-Request':id})}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,capability:cap,latency_ms:Date.now()-start,request_id:id,error:timed?'Upstream provider timed out':'Upstream provider request failed'},timed?504:502)}finally{clearTimeout(tm)}}};