import { resolveShotstackSource } from './shotstack-gateway';

const BASE = 'https://gateway.pixazo.ai';
const STATUS = `${BASE}/v2/requests/status/`;
const CONTRACT = '1.1';

function cors(r: Request, e: any) {
  const o = r.headers.get('Origin') || '';
  const allowed = String(e.ALLOWED_ORIGIN || '').split(',').map((x: string) => x.trim()).filter(Boolean);
  return {'Access-Control-Allow-Origin': o && (!allowed.length || allowed.includes(o)) ? o : (allowed[0] || '*'),'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-BeatVision-Contract,Authorization,X-BeatVision-Request','Access-Control-Max-Age':'86400'};
}
function json(r: Request, e: any, d: unknown, status = 200) { return new Response(JSON.stringify(d, null, 2), {status,headers:{'Content-Type':'application/json',...cors(r,e)}}); }
function auth(r: Request, e: any) { return !e.GATEWAY_TOKEN || r.headers.get('Authorization') === `Bearer ${e.GATEWAY_TOKEN}`; }
function firstImage(p: any) { const a = p?.images?.images || p?.images || []; const x = Array.isArray(a) ? a[0] : a; return x?.image_url || x?.url || x?.data_url || null; }
function promptFor(p: any, scene: any = null) { return ['BeatVision cinematic music-video artwork.','Preserve the established world, characters, environment and continuity.','Do not add text, logos or watermarks.',`Style: ${String(p?.style || '').slice(0,1400)}`,`World: ${JSON.stringify(p?.world || {}).slice(0,7000)}`,scene ? `Scene: ${JSON.stringify(scene).slice(0,5000)}` : 'Create a strong world establishing image.'].join('\n'); }
function mediaUrl(d: any) { return d?.output?.media_url?.[0] || d?.output?.media_url || d?.output || d?.imageUrl || d?.image_url || d?.url || null; }
async function pixazoFetch(path: string, key: string, body: any) { const res = await fetch(`${BASE}${path}`, {method:'POST',headers:{'Content-Type':'application/json','Cache-Control':'no-cache','Ocp-Apim-Subscription-Key':key},body:JSON.stringify(body)}); const text=await res.text(); let data:any; try{data=JSON.parse(text)}catch{data={raw:text}} if(!res.ok) throw new Error(`Pixazo ${res.status}: ${String(data?.message || data?.error || text).slice(0,1800)}`); return data; }
async function wait(request: Request, e: any, key: string, requestId: string, capability: string, model: string, started: number) { const deadline=Date.now()+90000; while(Date.now()<deadline){ const res=await fetch(`${STATUS}${encodeURIComponent(requestId)}`,{headers:{'Ocp-Apim-Subscription-Key':key,'Accept':'application/json'}}); const text=await res.text(); let data:any; try{data=JSON.parse(text)}catch{data={}} if(!res.ok) throw new Error(`Pixazo status ${res.status}: ${text.slice(0,1200)}`); const s=String(data?.status||'').toUpperCase(); if(s==='COMPLETED'){const url=mediaUrl(data); if(!url)throw new Error(`Pixazo ${model} completed without output media.`); return {url,data};} if(['ERROR','FAILED','CANCELLED'].includes(s))throw new Error(`Pixazo ${model} job ${s}: ${String(data?.error||'unknown error').slice(0,1600)}`); await new Promise(r=>setTimeout(r,3000)); } throw new Error(`Pixazo ${model} job did not complete within 90 seconds.`); }
async function generateImage(key:string, model:'flux'|'sd3-5'|'sdxl', prompt:string) {
  if(model==='flux') { const d=await pixazoFetch('/flux/text-to-image',key,{prompt,aspect_ratio:'16:9'}); if(d?.request_id){const x=await wait(new Request('https://local'),{},key,d.request_id,'image','flux-schnell',Date.now());return x.url;} return mediaUrl(d); }
  if(model==='sd3-5') { const d=await pixazoFetch('/sd3-5/v1/r-sd-3-5-large',key,{prompt,aspect_ratio:'16:9',cfg:5,steps:35,output_format:'webp',output_quality:90,prompt_strength:0.85}); if(d?.request_id){const x=await wait(new Request('https://local'),{},key,d.request_id,'image','sd3.5',Date.now());return x.url;} return mediaUrl(d); }
  const d=await pixazoFetch('/getImage/v1/getSDXLImage',key,{prompt,height:1024,width:1024,num_steps:20,guidance_scale:5}); if(d?.request_id){const x=await wait(new Request('https://local'),{},key,d.request_id,'image','sdxl',Date.now());return x.url;} return mediaUrl(d);
}
async function animate(r:Request,e:any,key:string,p:any,id:string){const raw=firstImage(p); if(!raw)return json(r,e,{ok:false,contract_version:CONTRACT,capability:'video',provider:'pixazo',status:'invalid_input',request_id:id,error:'No approved scene image was supplied.'},400); const started=Date.now(); try { const imageUrl=raw.startsWith('data:') ? await resolveShotstackSource(raw,e.SHOTSTACK_API_KEY||'', 'beatvision-scene.jpg') : raw; const scene=p?.storyboard?.scenes?.[0]||{}; const d=await pixazoFetch('/ltx/image-to-video',key,{prompt:promptFor(p,scene),image_url:imageUrl,resolution:e.PIXAZO_LTX_RESOLUTION||'720p',duration:Number(e.PIXAZO_LTX_DURATION||5),fps:Number(e.PIXAZO_LTX_FPS||25),aspect_ratio:'16:9'}); const rid=d?.request_id; if(!rid)throw new Error('Pixazo LTX did not return a request_id.'); const out=await wait(r,e,key,rid,'video','ltx',started); return json(r,e,{ok:true,contract_version:CONTRACT,capability:'video',provider:'pixazo',model:'ltx',status:'animated',delivery:'temporary_url',latency_ms:Date.now()-started,request_id:id,result:{status:'animated',video_url:out.url,source:'Pixazo free LTX image-to-video',pixazo_request_id:rid}}); } catch(err){return json(r,e,{ok:false,contract_version:CONTRACT,capability:'video',provider:'pixazo',model:'ltx',status:'provider_error',request_id:id,latency_ms:Date.now()-started,error:String(err instanceof Error?err.message:err).slice(0,2000)},502)} }

export default { async fetch(r:Request,e:any){
  if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r,e)});
  const id=r.headers.get('X-BeatVision-Request')||crypto.randomUUID();
  if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);
  if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);
  const key=e.PIXAZO_API_KEY; if(!key)return json(r,e,{ok:false,contract_version:CONTRACT,status:'provider_unavailable',provider:'pixazo',request_id:id,error:'PIXAZO_API_KEY is not configured.'},503);
  let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}
  const op=body?.operation; if(body?.contract_version!==CONTRACT)return json(r,e,{ok:false,error:'Expected BeatVision contract 1.1.',request_id:id},400); const p=body.payload||{};
  if(op==='animate')return animate(r,e,key,p,id);
  if(op==='worldAssets'){const started=Date.now();try{const [character,environment,hero]=await Promise.all([generateImage(key,'flux',promptFor(p)+' Focus on the primary recurring character concept, full body, clean silhouette.'),generateImage(key,'flux',promptFor(p)+' Focus on a defining environment/location from the world.'),generateImage(key,'sdxl',promptFor(p)+' Create a polished establishing keyframe for the world.')] );return json(r,e,{ok:true,contract_version:CONTRACT,capability:'image',provider:'pixazo',model:'flux+sdxl',latency_ms:Date.now()-started,request_id:id,result:{characters:[{name:'Primary BeatVision character',image_url:character}],environments:[{name:'Primary BeatVision environment',image_url:environment}],hero_image_url:hero,style_bible:p.world||null,models_used:['flux-schnell','sdxl']}})}catch(err){return json(r,e,{ok:false,contract_version:CONTRACT,capability:'image',provider:'pixazo',status:'provider_error',request_id:id,error:String(err instanceof Error?err.message:err).slice(0,2000)},502)}}
  if(op==='sceneImages'){const scenes=Array.isArray(p?.storyboard?.scenes)?p.storyboard.scenes.slice(0,8):[]; if(!scenes.length)return json(r,e,{ok:false,contract_version:CONTRACT,capability:'image',provider:'pixazo',status:'invalid_input',request_id:id,error:'Storyboard contains no scenes.'},400);const started=Date.now();try{const images=await Promise.all(scenes.map(async(s:any,i:number)=>({scene:Number(s.scene||i+1),status:'generated',image_url:await generateImage(key,'sd3-5',promptFor(p,s))})));return json(r,e,{ok:true,contract_version:CONTRACT,capability:'image',provider:'pixazo',model:'sd3.5',latency_ms:Date.now()-started,request_id:id,result:{images,models_used:['sd3.5']}})}catch(err){return json(r,e,{ok:false,contract_version:CONTRACT,capability:'image',provider:'pixazo',model:'sd3.5',status:'provider_error',request_id:id,error:String(err instanceof Error?err.message:err).slice(0,2000)},502)}}
  if(op==='generateMusic'){const started=Date.now();try{const d=await pixazoFetch('/tracks/v1/generate',key,{prompt:String(p?.music_prompt||p?.style||'cinematic instrumental music for a dark emotional music video').slice(0,5000),lyrics:String(p?.lyrics||'').slice(0,12000),instrumental:!p?.lyrics,duration:Math.max(10,Math.min(Number(p?.duration_seconds||30),600)),bpm:p?.bpm,key:p?.key});const rid=d?.request_id;if(rid){const out=await wait(r,e,key,rid,'audio','tracks',started);return json(r,e,{ok:true,contract_version:CONTRACT,capability:'music',provider:'pixazo',model:'tracks',latency_ms:Date.now()-started,request_id:id,result:{status:'generated',audio_url:out.url,pixazo_request_id:rid}})}return json(r,e,{ok:true,contract_version:CONTRACT,capability:'music',provider:'pixazo',model:'tracks',latency_ms:Date.now()-started,request_id:id,result:{status:'generated',audio_url:mediaUrl(d)}})}catch(err){return json(r,e,{ok:false,contract_version:CONTRACT,capability:'music',provider:'pixazo',status:'provider_error',request_id:id,error:String(err instanceof Error?err.message:err).slice(0,2000)},502)}}
  return json(r,e,{ok:false,error:`Pixazo route not implemented for operation: ${op}`,request_id:id},404);
} };
