const VIDEO_BASE='https://gen.pollinations.ai';
const MEDIA_BASE='https://media.pollinations.ai';
const VIDEO_MODEL='seedance-2.0-fast';
const AUDIO_BASE='https://gen.pollinations.ai';
const AUDIO_MODEL='whisper-large-v3';
const VIDEO_TIMEOUT_MS=120_000;
const UPSTREAM_TIMEOUT_MS=45_000;
const CONTRACT_VERSION='1.1';

function cors(r:Request,e:any){const o=r.headers.get('Origin')||'';const allowed=String(e.ALLOWED_ORIGIN||'').split(',').map((x:string)=>x.trim()).filter(Boolean);return{'Access-Control-Allow-Origin':o&&(!allowed.length||allowed.includes(o))?o:(allowed[0]||'*'),'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-BeatVision-Contract,Authorization,X-BeatVision-Request','Access-Control-Max-Age':'86400'}}
function json(r:Request,e:any,d:unknown,status=200){return new Response(JSON.stringify(d,null,2),{status,headers:{'Content-Type':'application/json',...cors(r,e)}})}
function auth(r:Request,e:any){return !e.GATEWAY_TOKEN||r.headers.get('Authorization')===`Bearer ${e.GATEWAY_TOKEN}`}
function clip(v:any,n:number){return typeof v==='string'?v.slice(0,n):v}
function safePayload(p:any){if(!p||typeof p!=='object')return{};const q=JSON.parse(JSON.stringify(p));for(const k of ['audio_base64','audio_data','file_base64','raw_audio'])delete q[k];return q}
function compactWorld(v:any){if(!v||typeof v!=='object')return v;return{title:clip(v.title,500),logline:clip(v.logline,3000),palette:Array.isArray(v.palette)?v.palette.slice(0,24):v.palette,tone:clip(v.tone,2000),visual_language:clip(v.visual_language,5000),locations:Array.isArray(v.locations)?v.locations.slice(0,12):v.locations,character_concept:clip(v.character_concept,5000),continuity_rules:Array.isArray(v.continuity_rules)?v.continuity_rules.slice(0,30):v.continuity_rules,visual_motifs:Array.isArray(v.visual_motifs)?v.visual_motifs.slice(0,30):v.visual_motifs}}
function compactAudio(v:any){if(!v||typeof v!=='object')return v;return{duration_seconds:v.duration_seconds??null,bpm:v.bpm??null,sections:Array.isArray(v.sections)?v.sections.slice(0,30):v.sections,energy_curve:Array.isArray(v.energy_curve)?v.energy_curve.slice(0,120):v.energy_curve,transcript:clip(v.text||v.transcript||v.result?.text||'',12000)}}
function compactAssets(v:any){if(!v||typeof v!=='object')return v;return{characters:Array.isArray(v.characters)?v.characters.slice(0,20):v.characters,environments:Array.isArray(v.environments)?v.environments.slice(0,20):v.environments,style_bible:compactWorld(v.style_bible)}}
function compactStoryboard(v:any){if(!v||typeof v!=='object')return v;return{scenes:Array.isArray(v.scenes)?v.scenes.slice(0,24).map((s:any)=>({scene:s.scene,description:clip(s.description,2500),emotion:clip(s.emotion,500),location:clip(s.location,500),visual_direction:clip(s.visual_direction,3000),transition:clip(s.transition,1000),continuity_notes:clip(s.continuity_notes,2000)})):v.scenes}}
function messages(op:string,p:any){const clean=safePayload(p),system='You are the BeatVision visual-world director. Return ONLY valid JSON. Preserve creative intent, continuity, and production usefulness. Do not invent lyrics.';const base={song_title:clip(clean.song_title,500),style:clip(clean.style,1500),lyrics:clip(clean.lyrics,12000)};if(op==='revealWorld')return[{role:'system',content:system+' Return {title,logline,palette,tone,visual_language,locations,character_concept,continuity_rules,visual_motifs}.'},{role:'user',content:JSON.stringify({task:op,...base,audio:compactAudio(clean.audio)})}];return[{role:'system',content:system+' Return {scenes:[{scene,description,emotion,location,visual_direction,transition,continuity_notes}]}.'},{role:'user',content:JSON.stringify({task:op,...base,world:compactWorld(clean.world),assets:compactAssets(clean.assets)})}]}
function parse(t:string){const s=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{return{raw:s}}}
function imagePrompt(p:any){return`BeatVision cinematic music video concept art. 16:9 cinematic composition. Style: ${clip(p?.style||'',1500)}. World: ${JSON.stringify(compactWorld(p?.world||{}))}. Storyboard: ${JSON.stringify(compactStoryboard(p?.storyboard||{}))}. Strong composition and character/environment continuity.`}
function audioBlob(v:any){if(typeof v!=='string'||!v)return null;const value=v.includes(',')?v.slice(v.indexOf(',')+1):v;try{const raw=atob(value);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:'audio/mpeg'})}catch{return null}}
function dataUrlBlob(v:any){if(typeof v!=='string'||!v.startsWith('data:'))return null;const comma=v.indexOf(',');if(comma<0)return null;const mime=(v.slice(5,comma).split(';')[0]||'image/jpeg');const raw=atob(v.slice(comma+1));const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:mime})}
function firstImage(p:any){const imgs=p?.images?.images||p?.images||[];const item=Array.isArray(imgs)?imgs[0]:imgs;return item?.image_url||item?.url||item?.data_url||null}
async function uploadMedia(blob:Blob,token:string,filename:string,signal:AbortSignal){const form=new FormData();form.append('file',blob,filename);const res=await fetch(`${MEDIA_BASE}/upload`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form,signal});const text=await res.text();if(!res.ok)throw new Error(`Pollinations media upload returned ${res.status}: ${text.slice(0,800)}`);const data=JSON.parse(text);if(!data?.url)throw new Error('Pollinations media upload returned no media URL');return data.url as string}

export default {async fetch(r:Request,e:any){const u=new URL(r.url);if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r,e)});const id=r.headers.get('X-BeatVision-Request')||crypto.randomUUID();if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);
if(u.pathname==='/v1/audio/analyze'){if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}if(body?.contract_version!==CONTRACT_VERSION||body?.operation!=='analyzeAudio')return json(r,e,{ok:false,error:'Operation does not match contract 1.1',request_id:id},400);const token=e.AUDIO_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN;if(!token)return json(r,e,{ok:false,error:'No Pollinations audio token configured.',request_id:id},503);const p=body.payload||{},audio=audioBlob(p.audio_base64||p.audio_data);if(!audio)return json(r,e,{ok:false,error:'Audio provider requires valid base64 audio.',request_id:id},400);const start=Date.now(),ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),120000);try{const form=new FormData();form.append('file',audio,'beatvision-audio');form.append('model',AUDIO_MODEL);form.append('response_format','verbose_json');form.append('temperature','0');const res=await fetch(`${AUDIO_BASE}/v1/audio/transcriptions`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'X-BeatVision-Request':id},body:form,signal:ctl.signal});const text=await res.text();let result:any;try{result=JSON.parse(text)}catch{result={raw:text.slice(0,10000)}}return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:'audio',provider:'pollinations',model:AUDIO_MODEL,latency_ms:Date.now()-start,request_id:id,result,analysis:{duration_seconds:p.duration_seconds??null,bpm:p.bpm??null,energy_curve:p.energy_curve??null,source:'Pollinations Whisper transcription + browser audio metadata'}},res.status)}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,contract_version:CONTRACT_VERSION,capability:'audio',provider:'pollinations',model:AUDIO_MODEL,request_id:id,error:timed?'Pollinations audio provider timed out after 120 seconds':`Pollinations audio provider request failed: ${err instanceof Error?err.message:'unknown error'}`},timed?504:502)}finally{clearTimeout(tm)}}

const languagePath=u.pathname==='/v1/language/world'||u.pathname==='/v1/language/storyboard';
const imagePath=u.pathname==='/v1/image/world-assets'||u.pathname==='/v1/image/scenes';
if(languagePath){if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}const op=u.pathname.endsWith('/world')?'revealWorld':'storyboard';if(body?.contract_version!==CONTRACT_VERSION||body?.operation!==op)return json(r,e,{ok:false,error:'Operation does not match contract 1.1',request_id:id},400);const token=e.LANGUAGE_PROVIDER_TOKEN;if(!token)return json(r,e,{ok:false,error:'No Pollinations language token configured.',request_id:id},503);const start=Date.now(),ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const clean=safePayload(body.payload||{}),res=await fetch(e.LANGUAGE_PROVIDER_URL||'https://gen.pollinations.ai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,'X-BeatVision-Request':id},body:JSON.stringify({model:e.LANGUAGE_PROVIDER_MODEL||'openai',messages:messages(op,clean),temperature:.7}),signal:ctl.signal});const text=await res.text();let result:any;try{result=JSON.parse(text)}catch{result={raw:text.slice(0,20000)}}const content=result?.choices?.[0]?.message?.content||'';return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:'language',provider:e.LANGUAGE_PROVIDER||'pollinations',model:e.LANGUAGE_PROVIDER_MODEL||'openai',latency_ms:Date.now()-start,request_id:id,result:content?parse(content):result},res.status)}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,error:timed?'Language provider timed out':`Language provider request failed: ${err instanceof Error?err.message:'unknown error'}`,request_id:id,capability:'language',provider:'pollinations'},timed?504:502)}finally{clearTimeout(tm)}}

if(imagePath){if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}const op=u.pathname.endsWith('/world-assets')?'worldAssets':'sceneImages';if(body?.contract_version!==CONTRACT_VERSION||body?.operation!==op)return json(r,e,{ok:false,error:'Operation does not match contract 1.1',request_id:id},400);const token=e.IMAGE_PROVIDER_TOKEN;if(!token)return json(r,e,{ok:false,error:'No Pollinations image token configured.',request_id:id},503);const start=Date.now(),ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const prompt=encodeURIComponent(imagePrompt(body.payload||{})),target=`https://gen.pollinations.ai/image/${prompt}?model=${encodeURIComponent(e.IMAGE_PROVIDER_MODEL||'flux')}`,res=await fetch(target,{method:'GET',headers:{Authorization:`Bearer ${token}`,'X-BeatVision-Request':id},signal:ctl.signal});if(!res.ok)return json(r,e,{ok:false,capability:'image',provider:'pollinations',model:e.IMAGE_PROVIDER_MODEL||'flux',request_id:id,error:`Pollinations image provider returned ${res.status}`,provider_response:(await res.text()).slice(0,4000)},res.status);const blob=await res.blob(),data=new Uint8Array(await blob.arrayBuffer());let s='';for(let i=0;i<data.length;i+=32768)s+=String.fromCharCode(...data.subarray(i,i+32768));const ct=blob.type||'image/jpeg';return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capability:'image',provider:'pollinations',model:e.IMAGE_PROVIDER_MODEL||'flux',latency_ms:Date.now()-start,request_id:id,result:{status:'generated',image_url:`data:${ct};base64,${btoa(s)}`,mime_type:ct}},200)}catch(err){const timed=(err as Error)?.name==='AbortError';return json(r,e,{ok:false,capability:'image',provider:'pollinations',model:e.IMAGE_PROVIDER_MODEL||'flux',request_id:id,error:timed?'Image provider timed out':`Image provider request failed: ${err instanceof Error?err.message:'unknown error'}`},timed?504:502)}finally{clearTimeout(tm)}}

if(u.pathname==='/v1/storage/asset'){if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);const target=e.STORAGE_PROVIDER_URL;if(!target)return json(r,e,{ok:false,error:'Storage provider is optional and not configured.',request_id:id},503);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400)}const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),UPSTREAM_TIMEOUT_MS);try{const headers:Record<string,string>={'Content-Type':'application/json','X-BeatVision-Request':id};if(e.STORAGE_PROVIDER_TOKEN)headers.Authorization=`Bearer ${e.STORAGE_PROVIDER_TOKEN}`;const res=await fetch(target,{method:'POST',headers,body:JSON.stringify({...body,request_id:id}),signal:ctl.signal});const text=await res.text();let result:any;try{result=JSON.parse(text)}catch{result={raw:text.slice(0,20000)}}return json(r,e,{ok:res.ok,contract_version:CONTRACT_VERSION,capability:'storage',request_id:id,result},res.status)}catch(err){return json(r,e,{ok:false,error:`Storage provider request failed: ${err instanceof Error?err.message:'unknown error'}`,request_id:id},502)}finally{clearTimeout(tm)}}

if(u.pathname==='/health')return json(r,e,{ok:true,status:'online',name:'BeatVision Provider Gateway',contract_version:CONTRACT_VERSION,request_id:id});
if(u.pathname==='/v1/capabilities')return json(r,e,{ok:true,contract_version:CONTRACT_VERSION,capabilities:{language:{configured:!!e.LANGUAGE_PROVIDER_TOKEN,provider:'pollinations',model:e.LANGUAGE_PROVIDER_MODEL||'openai'},image:{configured:!!e.IMAGE_PROVIDER_TOKEN,provider:'pollinations',model:e.IMAGE_PROVIDER_MODEL||'flux'},audio:{configured:!!(e.AUDIO_PROVIDER_TOKEN||e.LANGUAGE_PROVIDER_TOKEN),provider:'pollinations',model:AUDIO_MODEL},video:{configured:!!e.PIXAZO_API_KEY,provider:'pixazo',model:'ltx'},assembly:{configured:!!e.SHOTSTACK_API_KEY,provider:'shotstack-sandbox'},fallback:{configured:!!e.SHOTSTACK_API_KEY,provider:'shotstack-camera-motion'},storage:{configured:!!e.STORAGE_PROVIDER_URL,optional:true}},request_id:id});
return json(r,e,{ok:false,error:'Route not found',request_id:id},404)}};
